### ISSUE TITLE
Quicksetup unreadable comboboxtext widget

### ISSUE THREAD

**Issue by 01micko** [vanilla-dpup/unstable#1]
- [Page Down] works until the screen is full then no items for `locale` and `keyboard`
- `timezone` comboboxtext shows only black

![20220104_09h30m25s_grim](https://user-images.githubusercontent.com/1019119/147998206-4ef095ca-af8c-4bf3-bc39-4b0ac337e17e.png)

**Comment by 01micko** [comment]
In slacko gtkdialog segfaults under pure wayland running `quicksetup` and selecting 'timezone'. I'll post a backtrace later.

**Comment by dimkr** [comment]
Moved to puppylinux-woof-CE/woof-CE#3322.

**Comment by 01micko** [comment]
It's labwc up to v5.x that is the culprit

**Comment by dimkr** [comment]
I reproduced this under dwl, and dwl uses the scene graph API. The problem could be in wlroots if it's not specific to labwc.
