### ISSUE TITLE
devx or dkms is needed

### ISSUE THREAD

**Issue by mavrothal** [vanilla-dpup/unstable#3]
Tried [vanilladpup-x86_64-10.0.7-jwm](https://github.com/vanilla-dpup/unstable/releases/tag/vanilladpup-x86_64-10.0.7-jwm) briefly and came to the following problem. 
My laptop has no wired network and needs the broadcom-sta driver for network connection which of course I can not get with apt. I can get it in another machine but requires dkms >=2.1 that is missing. dkms also can not be installed from the package because it needs the (missing gcc) compiler. I could get the source and compile it but again all the dev tools are missing. So basically should get build-essential and any dependencies in another machine to get the wifi going.
You may consider adding the either devx or at least dkms in the builds.

**Comment by dimkr** [comment]
`apt install build-essential`, 10.0 won't include devx because apt **will** install gcc if you `apt install gcc` while devx is loaded.

**Comment by mavrothal** [comment]
Please read ALL the report above!
How can you ```apt``` anything WITHOUT network?

**Comment by dimkr** [comment]
> How can you apt anything WITHOUT network?

The same way you would on Debian: using a Debian DVD or something.

**Comment by dimkr** [comment]
(By the way, you can use `apt download` on another machine to download all the .deb packages you need)
