### ISSUE TITLE
drive icons fail to draw when scale is changed

### ISSUE THREAD

**Issue by mavrothal** [vanilla-dpup/unstable#4]
agin in vanilladpup-x86_64-10.0.7-jwm, if the monitor scale is changed (in my case to 1.5) the drive icons disappear. If you mount them with pmount they reappear in the expected position.
Restarting X, jwm or deleting .pup_event content, does not remedy the problem

**Comment by dimkr** [comment]
This doesn't belong here, should be in [puppylinux-woof-CE/woof-CE/issues](https://github.com/puppylinux-woof-CE/woof-CE/issues), under https://github.com/orgs/puppylinux-woof-CE/projects/1.
